apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: onec6n4xq-nodejs
  janus-idp.io/tekton: onec6n4xq-nodejs
  backstage.io/kubernetes-id: onec6n4xq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: onec6n4xq-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
